function [X,P,T] = RUNGE(X,P,T,H,F);

% ***** FOURTH-ORDER RUNGE-KUTTA FORMULAE (1.1.12) AND (1.1.13) ARE
% PROGRAMED IN THIS SUBROUTINE FOR SOLVING A SECOND-ORDER DIFFERENTIAL
% EQUATION REWRITTEN IN THE FORM :
% DX/DT = P AND DP/DT = F(X,P,T)
% H IS THE SIZE OF INCREMENT IN THE INDEPENDENT VARIABLE T, AND F IS A
% FUNCTION DEFINED IN ANOTHER SUBPROGRAM

D1X = H*P;
D1P = H*feval(F,X,P,T);
D2X = H*(P + D1P/2.);
D2P = H*feval(F,X+D1X/2.,P+D1P/2.,T+H/2.);
D3X = H*(P + D2P/2.);
D3P = H*feval(F,X+D2X/2.,P+D2P/2.,T+H/2.);
D4X = H*(P + D3P);
D4P = H*feval(F,X+D3X,P+D3P,T+H);
T = T + H;
X = X + (D1X + 2.*D2X + 2.*D3X + D4X)/6.;
P = P + (D1P + 2.*D2P + 2.*D3P + D4P)/6.;
