---
title: "Persamaan Navier-Stokes pada 2d"
author: "Fadjar Fathurrahman"
format:
  revealjs:
    smaller: true
---


## Pendahuluan {.scrollable}

Aliran fluida 2d, dijelaskan dengan vektor kecepatan (medan vektor):
$$
\mathbf{q} = u(x,y)\widehat{\mathbf{i}} + v(x,y)\widehat{\mathbf{j}}
$$
dan tekanan fluida (medan skalar)
$$
p(x,y)
$$

Persamaan konvervasi massa: 
$$
\nabla \cdot \mathbf{q} = 0
$$
atau:
$$
\frac{\partial u}{\partial x} + \frac{\partial v}{\partial y} = 0
$$

Konvervasi momentum:
$$
\frac{\partial q}{\partial t} + \mathrm{\nabla\cdot}(\mathbf{q} \otimes \mathbf{q}) =
-\nabla p + \frac{1}{\mathrm{Re}}\nabla\mathbf{q}
$$
atau dalam bentuk eksplisit:
$$
\begin{align*}
\frac{\partial u}{\partial t}+\frac{\partial u^{2}}{\partial x}+\frac{\partial uv}{\partial y} & =-\frac{\partial p}{\partial x}+\frac{1}{\mathrm{Re}}\left(\frac{\partial^{2}u}{\partial x^{2}}+\frac{\partial^{2}u}{\partial y^{2}}\right)\\
\frac{\partial v}{\partial t}+\frac{\partial uv}{\partial x}+\frac{\partial v^{2}}{\partial y} & =-\frac{\partial p}{\partial y}+\frac{1}{\mathrm{Re}}\left(\frac{\partial^{2}v}{\partial x^{2}}+\frac{\partial^{2}v}{\partial y^{2}}\right)
\end{align*}
$$
dengan $\mathrm{Re}$ adalah bilangan Reynolds:
$$
\mathrm{Re}=\frac{V_{0}L}{\nu}
$$


## Metode fractional-step {.scrollable}

Menggunakan metode \emph{fractional-step}:

- Predictor step, menyelesaikan persamaan momentum yang ditulis dalam bentuk:
$$
\frac{\partial q}{\partial t}=-\mathcal{G}p+\mathcal{H}+\frac{1}{\mathrm{Re}}\nabla^{2}q
$$



## Algoritma Thomas {.scrollable}

Algoritma Thomas dapat digunakan untuk menyelesaikan sistem persamaan linear:
$$
\mathbf{A}\mathbf{x} = \mathbf{f}
$$
dengan $\mathbf{A}$ adalah matriks tridiagonal:
$$
\mathbf{A} =
\begin{bmatrix}
b_{1} & c_{1} & 0 & \cdots & \cdots & 0 & 0 \\
a_{2} & b_{2} & c_{2} & 0 & \cdots & 0 & 0 \\
\cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots \\
\cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots \\
0 & 0 & 0 & 0 & a_{n-1} & b_{n-1} & c_{n-1} \\
0 & 0 & 0 & 0 & \cdots & a_{n} & b_{n}
\end{bmatrix}
$$
vektor $\mathbf{x}$
$$
\mathbf{x} =
\begin{bmatrix}
x_{1}\\
x_{2}\\
\vdots\\
\vdots\\
x_{n-1}\\
x_{n}
\end{bmatrix}
$$
dan vektor $\mathbf{f}$:
$$
\begin{bmatrix}
f_{1}\\
f_{2}\\
\vdots\\
\vdots\\
f_{n-1}\\
f_{n}
\end{bmatrix}
$$
dengan menggunakan hubungan perulangan (_recurrence relation_):
$$
\begin{align}
x_{k} & =\gamma_{k} - \frac{c_{k}}{\beta_{k}}x_{k+1},\qquad k=1,\ldots,(n-1)\\
x_{n} & =\gamma_{n}
\end{align}
$$ {#eq-recurrence-12-67}
Dengan mensubstitusikan hubungan perulangan tersebut pada persamaan linear awal
diperoleh koefisien $\gamma_{k}$ dan $\beta_{k}$:
$$
\begin{align}\beta_{1} & = b_{1} \\
\beta_{k} & = b_{k}-\frac{c_{k-1}}{\beta_{k-1}}a_{k},\qquad k=2,\ldots,n
\end{align}
$$
dan
$$
\begin{align}
\gamma_{1} & = \frac{f_{1}}{\beta_{1}} = \frac{f_{1}}{b_{1}} \\
\gamma_{k} & = \frac{f_{k}-a_{k}\gamma_{k-1}}{\beta_{k}}, \qquad k = 2,\ldots,n
\end{align}
$$

Setelah koefisien $\gamma_{k}$ dan $\beta_{k}$ dihitung, variabel yang tidak diketahui,
yaitu $x_{k}$ dapat dihitung dengan substitusi balik menggunakan hubungan perulangan
(@eq-recurrence-12-67).

## Ilustrasi Algoritma Thomas

Tinjau tiga persamaan linear:
$$
\begin{align}
b_{1} x_{1} + c_{1} x_{2}               & = f_{1} \\
a_{2} x_{1} + b_{2} x_{2} + c_{2} x_{3} & = f_{2} \\
            + a_{3} x_{2} + b_{3} x_{3} & = f_{3}
\end{align}
$$

Persamaan pertama:
$$
b_{1} x_{1} + c_{1} x_{2} = f_{1}
$$
Hubungan perulangan:
$$
x_{1} = \gamma_{1} - \dfrac{c_{1}}{\beta_{1}} x_{2} \\
x_{2} = \gamma_{2} - \dfrac{c_{2}}{\beta_{2}} x_{3}
x_{3} = \gamma_{3}
$$

$$
b_{1}\left( \gamma_{1} - \dfrac{c_{1}}{\beta_{1}} x_{2} \right) + c_{1} x_{2} = f_{1}
$$


## Contoh

$$
\frac{\partial u}{\partial t}-\nabla^{2}u(t,x,y)=f(x,y)
$$

untuk $(x,y)\in\Omega=\left[0,L_{x}\right]\times\left[0,L_{y}\right]$
menggunakan syarat batas periodik.

Pada keadaan tunak:
\[
-\nabla^{2}u_{s}(x,y)=f(x,y)
\]

Fungsi untuk RHS:
\[
f(x,y)=(a^{2}+b^{2})\sin(ax)\cos(by)
\]
dengan $a=\dfrac{2\pi}{L_{x}}$ dan $b=\dfrac{2\pi}{L_{y}}$.

Solusi eksak:
\[
u_{\mathrm{exact}}(x,y)=\sin(ax)\cos(by)
\]

\end{document}
