function [XNEXT,YNEXT] = RUNTTA(X,Y,H,F1,F2);

% ***** INTEGRATION OF THE SIMULTANEOUS FIRST-ORDER EQUATIONS DX/DT =
% F1(X,Y) AND DY/DT = F2(X,Y) USING FOURTH-ORDER RUNGE-KUTTA METHOD. XNEXT
% AND YNEXT ARE THE VALUES OF X AND Y, RESPECTIVELY, AT T+H *****

D1X = H*feval(F1,X,Y);
D1Y = H*feval(F2,X,Y);
D2X = H*feval(F1,X+D1X/2.,Y+D1Y/2.);
D2Y = H*feval(F2,X+D1X/2.,Y+D1Y/2.);
D3X = H*feval(F1,X+D2X/2.,Y+D2Y/2.);
D3Y = H*feval(F2,X+D2X/2.,Y+D2Y/2.);
D4X = H*feval(F1,X+D3X,Y+D3Y);
D4Y = H*feval(F2,X+D3X,Y+D3Y);
XNEXT = X + (D1X + 2.*D2X + 2.*D3X + D4X)/6.;
YNEXT = Y + (D1Y + 2.*D2Y + 2.*D3Y + D4Y)/6.;
