function [C,F] = TRID(C,N);

% ***** SOLVING A SET OF N LINEAR SIMULTANEOUS EQUATIONS DESCRIBED BY
% (2.2.13) HAVING A TRIDIAGONAL COEFFICIENT MATRIX. COEFFICIENT MATRICES 
% ARE REPRESENTED BY C(I,J) AND THE SOLUTION IS STORED IN THE
% ONE-DIMENSIONAL ARRAY F(I) *****

% ***** ELIMINATE THE FIRST TERM OF EACH OF THE EQUATIONS (EXCEPT THE FIRST
% AND THE LAST ONE) ACCORDING TO (2.2.14) *****

for I=2:N-1
    C(I,2) = C(I,2)*C(I-1,2) - C(I,1)*C(I-1,3);
    C(I,3) = C(I,3)*C(I-1,2);
    C(I,4) = C(I,4)*C(I-1,2) - C(I,1)*C(I-1,4);
end

% ***** COMPUTE SOLUTION USING (2.2.15) AND (2.2.16) *****

F(N) = ( C(N,4)*C(N-1,2)-C(N,1)*C(N-1,4) ) / ( C(N,2)*C(N-1,2)-C(N,1)*C(N-1,3) );

for K=1:N-1
    J = N-K;
    F(J) = ( C(J,4)-C(J,3)*F(J+1) ) / C(J,2);
end