if ~exist('show_material_mesh','var') 
    show_material_mesh = true;
end
if (show_material_mesh == true)
    save('mesh_data_file', 'eps_r_x', 'eps_r_y', 'eps_r_z', ...
        'mu_r_x', 'mu_r_y', 'mu_r_z',...
        'sigma_e_x', 'sigma_e_y', 'sigma_e_z', ...
        'sigma_m_x', 'sigma_m_y', 'sigma_m_z', ...
        'nx','ny','nz','dx','dy','dz', 'fdtd_domain');
    display_material_mesh_gui;
end
