% update electric fields 

current_time  = current_time + dt/2;

% TMz
if is_TEz
    Ex(1:nx,2:ny) = Cexe(1:nx,2:ny).*Ex(1:nx,2:ny) ...
                         + Cexhz(1:nx,2:ny).*...
                         (Hz(1:nx,2:ny)-Hz(1:nx,1:nym1));   

    Ey(2:nx,1:ny) = Ceye(2:nx,1:ny).*Ey(2:nx,1:ny) ...
                          + Ceyhz(2:nx,1:ny).*  ...
                          (Hz(2:nx,1:ny)-Hz(1:nxm1,1:ny)); 
end

% TMz
if is_TMz
    Ez(2:nx,2:ny) = ...
        Ceze(2:nx,2:ny).*Ez(2:nx,2:ny) ...
        + Cezhy(2:nx,2:ny) ...
        .* (Hy(2:nx,2:ny)-Hy(1:nxm1,2:ny)) ...
        + Cezhx(2:nx,2:ny) ...
        .* (Hx(2:nx,2:ny)-Hx(2:nx,1:nym1));
end
