function [XX1, YY1, NPOINT] = MAPPNG(X1, Y1, K1, XMIN, XMAX, YMIN, YMAX);

% ***** THIS SUBROUTINE EXAMINES EACH OF THE K1 POINTS (X1,Y1) IN Z1-PLANE
% AND THROWS AWAY THE POINTS INSIDE THE CIRCLE THAT MAPS INTO THE AIRFOIL
% AFTER MAPPING THE REMAINING POINTS ONTO Z-PLANE THROUGH JOUKOWSKI 
% TRANSFORMATION, ONLY THOSE WHICH ARE WITHIN THE FRAME BOUNDED BY XMIN, 
% XMAX, YMIN AND YMAX ARE RETAINED. THESE POINTS, OF TOTAL NUMBER NPOINT,
% ARE RETURNED TO THE MAIN PROGRAM AS POINTS OF COORDINATES (X1,Y1) IN 
% Z-PLANE *****

global A B C ZP1;

XX1 = zeros(K1);
YY1 = zeros(K1);

NPOINT = 0;

for I=1:K1

    Z1 = X1(I) + Y1(I)*i;
    Z2 = Z1 - ZP1;
    R = abs(Z2);

    if ( R >= C*A )
        Z = Z1 + B^2/Z1;
        X = real(Z);
        Y = imag(Z);
    end

    if (X >= XMIN | X <= XMAX | Y >= YMIN | Y <= YMAX)
        NPOINT = NPOINT + 1;
        XX1(NPOINT) = X;
        YY1(NPOINT) = Y;
    end

end
